<?= $this->doctype() ?>
<html>
<head>
	<meta charset="utf-8">
	<?= $this->headTitle('Christmas Dash')->setSeparator(' - ')->setAutoEscape(false) ?>

	<?= $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
    ?>

    <!-- Le styles -->
        <?= $this->headLink()
            ->prependStylesheet($this->basePath('css/style.css'))
            ->prependStylesheet($this->basePath('css/bootstrap-theme.min.css'))
            ->prependStylesheet($this->basePath('css/bootstrap.min.css'))
            ->prependStylesheet($this->basePath('css/form.css'))
        ?>

        <!-- Scripts -->
        <?= $this->headScript()
            ->prependFile($this->basePath('js/bootstrap.min.js'))
            ->prependFile($this->basePath('js/jquery-3.1.0.min.js'))
        ?>

	 <!-- game music -->
	 
	 <iframe src="<?= $this->basePath('audio/bgm1.mp3') ?>" controls muted allow="autoplay" id="audio" style="display: none;" ></iframe> 
				
	  <audio  controls autoplay loop hidden>
	        <source src="<?= $this->basePath('audio/bgm.mp3') ?>"  type="audio/mp3">
	    	<source src="<?= $this->basePath('audio/bgm.ogg') ?>" type="audio/ogg">
	</audio>
</head>

<body background="<?= $this->basePath('img/bd.gif') ?>" style="background-repeat: no-repeat;
    background-size: 1600px 1000px;">
    <div class="container">
    	<?= $this->content ?>
    </div>

</body>
</html>