<?= $this->doctype() ?>
<html>
<head>
  <meta charset="utf-8">
  <?= $this->headTitle('Christmas Dash')->setSeparator(' - ')->setAutoEscape(false) ?>

  <?= $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
    ?>

    <!-- Le styles -->
        <?= $this->headLink()
            ->prependStylesheet($this->basePath('css/style.css'))
            ->prependStylesheet($this->basePath('css/bootstrap-theme.min.css'))
            ->prependStylesheet($this->basePath('css/bootstrap.min.css'))
            ->prependStylesheet($this->basePath('css/form.css'))
        ?>

        <!-- Scripts -->
        <?= $this->headScript()
            ->prependFile($this->basePath('js/bootstrap.min.js'))
            ->prependFile($this->basePath('js/jquery-3.1.0.min.js'))
        ?>

   <!-- game music -->
   
   <iframe src="<?= $this->basePath('audio/bgm1.mp3') ?>" controls muted allow="autoplay" id="audio" style="display: none;" ></iframe> 
        
    <audio  controls autoplay loop hidden>
          <source src="<?= $this->basePath('audio/bgm.mp3') ?>"  type="audio/mp3">
        <source src="<?= $this->basePath('audio/bgm.ogg') ?>" type="audio/ogg">
  </audio>
</head>

<body background="<?= $this->basePath('img/bd.gif') ?>" style="background-repeat: no-repeat;
     
    background-size: 1700px 1200px;">

    <div class="container">
      <style type="text/css">
  .icon {
  position: absolute;
  /* Adjust these values accordingly */
  top: 0px;
  right: 50px;
  }
  <style>
.introbg {
    bottom: 100px;
    border: 10px solid #ffffff;
}
.bgcolor{
  background-color: #ffffff;
  border-radius: 50px;
  border-width: thin;
  border-color: coral;
}
</style>
</style>

<!-- extra css -->
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css" integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU" crossorigin="anonymous">
<link href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
  rel="stylesheet" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" 
  crossorigin="anonymous">

 <!-- extra js -->
   <script
  src="https://code.jquery.com/jquery-3.3.1.min.js"
  integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8="
  crossorigin="anonymous"></script>
  
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.bundle.min.js" integrity="sha384-pjaaA8dDz/5BgdFUPX6M/9SUZv4d12SUPF0axWc+VRZkx5xU3daN+lYb49+Ax+Tl" crossorigin="anonymous"></script>

<!-- content body -->
<div class="text-center" style="padding:50px 0">
<div class="logo">Christmas Dash</div>
<p style="color: yellow; font-size: 40px;">High Score:
  <?php 
        if(!empty($this->score)){
          echo $this->score;
        }
        else{
          echo '0';
        }
  ?></p>
<div class="icon">
  <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModalCenter">
  <i class="fas fa-cogs" style="font-size:60px; color:white; text-shadow:2px 2px 4px #000000;" ></i>
  </button>
</div>
<!-- Modal -->
<div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLongTitle">Settings</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <form name= "setPassword" id="setPassword" method="post">
      <div class="modal-body">
        <?php if(!empty($this->message)){
            echo '<div class="alert alert-danger" role="alert">'.$this->message .'div';
          }?>
        Old Password:
        <input type="Password" name="oldPassword" class="rounded" required=""><br>
        New Password:
        <input type="Password" name="newPassword" class="rounded" required="">
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
       
        <input type="submit" value="Save Changes" class="btn btn-primary"/>
        <button type="button" onclick="logOut()" class="btn btn-danger">Log Out</button>
      </div>
    </form>
      
      <script >
                      $(function(){
                  $('#setPassword').on('submit', function(e){
                      e.preventDefault();
                      $.ajax({
                          url: '/application/changePassword', //this is the submit URL
                          type: 'POST', //or POST
                          data: $('#setPassword').serialize(),
                          success: function(data){
                            alert(data);
                            data = JSON.parse(data);
                            
                               if(data.status == 'ok'){
                                  alert('ok');
                               } else {
                                  alert('not ok');
                               }
                          }
                      });
                  });
              });

              function logOut(){
                window.location.href = "/application/logout";
              }
      </script>
    


    </div>
  </div>
</div>

   <a href ="<?= $this->basePath('application/game') ?>"><img src="<?= $this->basePath('img/play.gif') ?>"></a>
    <div class="introbg ">
     <p><img class="bgcolor" src="<?= $this->basePath('img/introgame2.gif') ?>" height="150" width="250"></p>

</div>
    </div>

</body>
</html>