<!doctype html> 
<html lang="en"> 
<head> 
     <title>Bootstrap Example</title>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

        <style>
            .button1 {
                position: absolute;
                top: 85%;
                right: 65%;
            }

            .button2 {
                position: absolute;
                top: 85%;
                right: 35%;
            }
        </style>
            <iframe src="<?= $this->basePath('audio/bgm1.mp3') ?>" controls muted allow="autoplay" id="audio" style="display: none;" ></iframe> 
      <audio  controls autoplay loop hidden>
            <source src="<?= $this->basePath('audio/gameover.mp3') ?>"  type="audio/mp3">
    </audio>
</head>
<body background = "<?= $this->basePath('img/bd.gif') ?>" style="background-repeat: no-repeat;
     
    background-size: 1700px 1200px;">
    <p><img src="<?= $this->basePath('img/gameover.gif') ?>" style=" min-height: 150px;
    min-width: 150px;
    margin-left: auto;
    margin-right: auto;
    text-align: center;
    display: table-cell;
    vertical-align: middle;" ></p>

    <a class = "btn btn-success btn-lg button1 pull-right" href = "<?= $this->basePath('application/game') ?>" role = "button">Play Again</a>
     <a class = "btn btn-info btn-lg button2" href = "<?= $this->basePath('/application/play') ?>" role = "button">Main Menu</a>
</body>
</html>